# Generated by Django 2.2.6 on 2020-03-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_hunt_app', '0003_auto_20200331_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongArtist',
        ),
    ]
