# Generated by Django 2.2.6 on 2020-03-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_hunt_app', '0004_delete_songartist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSongArtist',
            new_name='SongArtist',
        ),
    ]
