# Generated by Django 2.2.6 on 2020-04-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_hunt_app', '0006_testsongartist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSongArtist',
        ),
    ]
